---
- name: Clone iNCIPit git repository
  ansible.builtin.git:
    repo: "{{ incipit_repo }}"
    dest: "/home/{{ opensrf_system_user }}/incipit"
    version: "{{ incipit_version }}"
  become: yes
  become_user: "{{ opensrf_system_user }}"
- name: Copy CGI file
  ansible.builtin.copy:
    remote_src: yes
    src: "/home/{{ opensrf_system_user }}/incipit/iNCIPit.cgi"
    dest: "{{ opensrf_install_prefix }}/var/cgi-bin/iNCIPit.cgi"
    owner: "{{ opensrf_system_user }}"
    group: "{{ opensrf_system_user }}"
    mode: u=rwx,g=rwx,o=rx
  become: yes
  become_user: "{{ opensrf_system_user }}"
- name: Create Config file
  ansible.builtin.template:
    src: iNCIPit.ini.j2
    dest: "{{ opensrf_install_prefix }}/var/cgi-bin/iNCIPit.ini"
    owner: "{{ opensrf_system_user }}"
    group: "{{ opensrf_system_user }}"
    mode: u=rw,g=rw,o=r
  become: yes
  become_user: "{{ opensrf_system_user }}"
- name: Create Pickup Libraries Config
  ansible.builtin.template:
    src: pickup-libs.j2
    dest: "{{ opensrf_install_prefix }}/var/cgi-bin/pickup-libs"
    owner: "{{ opensrf_system_user }}"
    group: "{{ opensrf_system_user }}"
    mode: u=rw,g=rw,o=r
  become: yes
  become_user: "{{ opensrf_system_user }}"
