---
- name: Clone NCIPServer git repository
  git:
    repo: 'https://github.com/iNCIPit/iNCIPit.git'
    dest: "/home/{{ evergreen_install_username }}/NCIPServer"
    version: HEAD
  become: yes
  become_user: "{{ evergreen_install_username }}"
