---
- name: Clone NCIPServer git repository
  git:
    repo: "{{ evergreen_incipit_repo }}"
    dest: "/home/{{ evergreen_install_username }}/incipit"
    version: "{{ evergreen_incipit_version }}"
  become: yes
  become_user: "{{ evergreen_install_username }}"
