---
- name: Check if evergreen autogen exists
  stat:
    path: /openils/bin/autogen.sh
  register: evergreen_autogen
- name: Fail out if Evergreen autogen doesn't exist
  fail:
    msg: "Evergreen doesn't seem to be installed. NCIP needs to be on an Evergreen app server."
  when: not evergreen_autogen.stat.exists
- name: Install perl prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libfile-slurp-perl
    - libmodern-perl-perl
    - libconfig-merge-perl
    - libdancer-perl
    - libobject-tiny-perl
    - libxml-libxml-simple-perl
    - libplack-perl
